name: smart_stock
description: "A application to use on stock"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.1
  auto_route: ^10.1.2
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  forui: ^0.16.0
  get_it: ^9.1.0
  google_fonts: ^6.3.1
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  riverpod_generator: ^3.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar-placeholder.jpg
    - assets/images/logo-newland-white.svg
    - assets/images/stock.png
    - assets/audios/store-scanner-beep.mp3
    - .env
